### ISSUE TITLE
Getting Initialization Error when running cucumber-selenium-fw

### ISSUE THREAD

**Issue by automationfraternity1** [VisionITTesting/question-and-answer-forum#1]
Hi Getting this error when running the Runner file.

![WhatsApp Image 2020-10-08 at 12 04 30 AM(1)](https://user-images.githubusercontent.com/66528120/95984213-7b0bd180-0e40-11eb-8ef4-16bc345da5da.jpeg)

@akashdktyagi

**Comment by akashdktyagi** [comment]
Most of the time reason for the errors are right there but we just ignore to investigate. @Yuraj for your error as well, error reason is also given by the java compiler, you just did not check it. The error clearly says that you have a mistake in the Feature file due to incorrect syntax.
 Check the error: "Failed to Parse resource at: classpath:feature...". Also, had to opened the HealthCheck.feature file who would have seen the error. Now you tell me why there is an error at line 1 in the HealthCheck.feature file in ur project.

<img width="925" alt="Screenshot 2020-10-10 at 11 38 44 AM" src="https://user-images.githubusercontent.com/10477349/95984656-23ba3100-0e41-11eb-9767-0c5d13b6c1d9.png">

**Comment by sarangholey** [comment]
> Hi Getting this error when running the Runner file.
> 
> ![WhatsApp Image 2020-10-08 at 12 04 30 AM(1)](https://user-images.githubusercontent.com/66528120/95984213-7b0bd180-0e40-11eb-8ef4-16bc345da5da.jpeg)
> 
> @akashdktyagi

The ":" creating the issue, correct it as
line no 2 - "Feature:"

**Comment by sarangholey** [comment]
Issue Answered

**Comment by mohangitac** [comment]
Hi Can you please suggest .properties and .cofig files content, Same error for me, but it's not get resolved

**Comment by mohangitac** [comment]
How to initialize the Report?
