### ISSUE TITLE
Array Initialisation Doubt

### ISSUE THREAD

**Issue by Roshani26149** [VisionITTesting/question-and-answer-forum#5]
Why ArrayList<Employee> emp=new ArrayList<>();
   emp.add(new Employee("Smith",45000,male);
  why we write new employee ,we can also write direct emp.add("smith",45000,male); but when i complile that its give me hashcode. little confused.

**Comment by akashdktyagi** [comment]
`
ArrayList emp=new ArrayList<>();

emp.add(new Employee("Smith",45000,male);
`
Above array list is capable of storing any object. In the above example you are trying to store a "new" employee object with three attributes with in it. 

However, later you are trying to add three values in a single add statement which is syntactically wrong because "add" method only accepts one argument with Type "object", not three arguments.

@Roshani26149

**Comment by Roshani26149** [comment]
Ya ...that's make me more clear..add() accept one argument.....

Thank you sir..
