### ISSUE TITLE
Why we Write----- WebDriver driver =new ChromeDriver();  insteade of SearchContext search=new ChromeDriver(); ??

### ISSUE THREAD

**Issue by Roshani26149** [VisionITTesting/question-and-answer-forum#6]
Inside SearchContext interface we have FindElement and FindElements methods. and inside WebDriver interface we have add(),addAll(), and again more method .if we write only searchcontext then we cannot use these methods.so better to use WebDriver and inherit SearchContext interface.
IS it Right or something else??

**Comment by akashdktyagi** [comment]
![image](https://user-images.githubusercontent.com/10477349/99418210-c96d2e00-2920-11eb-9604-68a5797901f2.png)

**Comment by akashdktyagi** [comment]
Check the above Class diagram; if you write SearchContext driver = new ChromeDriver(), then it will not give you the error message because parent class/interface can be used to save child object. But you can not use the methods which is not in the parent class. Search Context class is the parent interface but it has only two abstract methods. Since it has only two methods you can only invoke these two methods and nothing else. All the other usefull methods defined in the ChromeDriver class like get, close, quit etc you will not be able to call.

**Comment by akashdktyagi** [comment]
@Roshani26149
